apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-service
  title: Demo Service
  description: Sample service registered from my personal GitHub to learn Backstage.
  tags:
    - demo
    - nodejs
  annotations:
    github.com/project-slug: albalau-dev/demo-service
spec:
  type: service
  lifecycle: experimental
  owner: user:albalau-dev
